sudo: false
language: bash
os:
  - linux

script:
  - wget http://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz
  - tar xf arduino-1.8.8-linux64.tar.xz
  - mv arduino-1.8.8 $HOME/arduino_ide
  - export PATH="$HOME/arduino_ide:$PATH"
  - which arduino
  - mkdir -p $HOME/Arduino/libraries
  - cp -r $TRAVIS_BUILD_DIR $HOME/Arduino/libraries/AsyncOpenweathermapClient
  - cd $HOME/Arduino/libraries
  - git clone https://github.com/thijse/Arduino-Log.git
  - git clone https://github.com/me-no-dev/ESPAsyncTCP.git
  - git clone https://github.com/squix78/json-streaming-parser.git
  - source $TRAVIS_BUILD_DIR/travis/common.sh
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs 2>&1
  - arduino --install-boards esp8266:esp8266
  - arduino --install-library USBHost > /dev/null 2>&1
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --get-pref sketchbook.path
  - build_sketches arduino $HOME/Arduino/libraries/AsyncOpenweathermapClient esp8266

notifications:
  email:
    on_success: change
    on_failure: change


